import type { WebsiteOrbTarget, WebsiteOrbTargetId } from "./websiteOrbTargetTypes";

export const POINTER_TARGETS: Record<WebsiteOrbTargetId, WebsiteOrbTarget> = {
  "pops.nav.access": {
    id: "pops.nav.access",
    route: "/",
    selector: '[data-orb-target="pops.nav.access"]',
    label: "Access navigation",
    description: "The main navigation link that takes visitors to POPS access options.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.nav.get-pops": {
    id: "pops.nav.get-pops",
    route: "/",
    selector: '[data-orb-target="pops.nav.get-pops"]',
    label: "Get POPS button",
    description: "The primary site-wide call to open the POPS access page.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.home.what-is-pops": {
    id: "pops.home.what-is-pops",
    route: "/",
    selector: '[data-orb-target="pops.home.what-is-pops"]',
    label: "What POPS does",
    description: "The home-page section explaining how POPS turns scattered proof into a structured record.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.home.capture": {
    id: "pops.home.capture",
    route: "/",
    selector: '[data-orb-target="pops.home.capture"]',
    label: "Capture records",
    description: "The feature card about capturing incidents, messages, files, dates, and court-order context.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.home.evidence-vault": {
    id: "pops.home.evidence-vault",
    route: "/",
    selector: '[data-orb-target="pops.home.evidence-vault"]',
    label: "Preserve evidence",
    description: "The feature card about originals, SHA-256 hashing, and evidence integrity.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.home.records": {
    id: "pops.home.records",
    route: "/",
    selector: '[data-orb-target="pops.home.records"]',
    label: "Organize records",
    description: "The feature card about timelines, evidence indexes, incident logs, and attorney-ready packets.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.home.local-first": {
    id: "pops.home.local-first",
    route: "/",
    selector: '[data-orb-target="pops.home.local-first"]',
    label: "Local-first principle",
    description: "The home-page feature explaining that the app keeps local authority over records and exports.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.options": {
    id: "pops.access.options",
    route: "/access",
    selector: '[data-orb-target="pops.access.options"]',
    label: "POPS access options",
    description: "The access page section where visitors compare Guardian, Open Door, sponsor, and membership paths.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.standard": {
    id: "pops.access.standard",
    route: "/access",
    selector: '[data-orb-target="pops.access.standard"]',
    label: "Guardian Access",
    description: "The standard one-time POPS desktop app license option.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.hardship": {
    id: "pops.access.hardship",
    route: "/access",
    selector: '[data-orb-target="pops.access.hardship"]',
    label: "Open Door Access",
    description: "The contribution-based access path for fathers who cannot carry the full license price today.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.sponsor": {
    id: "pops.access.sponsor",
    route: "/access",
    selector: '[data-orb-target="pops.access.sponsor"]',
    label: "Sponsor a Father",
    description: "The sponsorship path that helps fund access for Open Door users.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.membership": {
    id: "pops.access.membership",
    route: "/access",
    selector: '[data-orb-target="pops.access.membership"]',
    label: "POPS Membership",
    description: "The one-time lifetime POPS membership option.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.checkout": {
    id: "pops.access.checkout",
    route: "/access",
    selector: '[data-orb-target="pops.access.checkout"]',
    label: "Checkout form",
    description: "The checkout area shown after a visitor chooses a direct purchase path.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.activation": {
    id: "pops.access.activation",
    route: "/access",
    selector: '[data-orb-target="pops.access.activation"]',
    label: "Open Door review steps",
    description: "The review and activation steps for Open Door Access.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
  "pops.access.local-first": {
    id: "pops.access.local-first",
    route: "/access",
    selector: '[data-orb-target="pops.access.local-first"]',
    label: "Local-first security",
    description: "The access-page section explaining local storage, hashing, backups, and offline operation.",
    actions: ["scroll_to_target", "ping", "explain"],
    guideOnly: true,
  },
};

export function getPointerTarget(targetId: string | undefined): WebsiteOrbTarget | null {
  if (!targetId) return null;
  return POINTER_TARGETS[targetId as WebsiteOrbTargetId] || null;
}

